// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpflsm

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadEnforcer returns the embedded CollectionSpec for enforcer.
func loadEnforcer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EnforcerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load enforcer: %w", err)
	}

	return spec, err
}

// loadEnforcerObjects loads enforcer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*enforcerObjects
//	*enforcerPrograms
//	*enforcerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadEnforcerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadEnforcer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// enforcerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type enforcerSpecs struct {
	enforcerProgramSpecs
	enforcerMapSpecs
}

// enforcerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type enforcerProgramSpecs struct {
	XdpDropTcpPorts *ebpf.ProgramSpec `ebpf:"xdp_drop_tcp_ports"`
}

// enforcerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type enforcerMapSpecs struct {
	Buffer   *ebpf.MapSpec `ebpf:"buffer"`
	PortData *ebpf.MapSpec `ebpf:"port_data"`
}

// enforcerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadEnforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type enforcerObjects struct {
	enforcerPrograms
	enforcerMaps
}

func (o *enforcerObjects) Close() error {
	return _EnforcerClose(
		&o.enforcerPrograms,
		&o.enforcerMaps,
	)
}

// enforcerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadEnforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type enforcerMaps struct {
	Buffer   *ebpf.Map `ebpf:"buffer"`
	PortData *ebpf.Map `ebpf:"port_data"`
}

func (m *enforcerMaps) Close() error {
	return _EnforcerClose(
		m.Buffer,
		m.PortData,
	)
}

// enforcerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadEnforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type enforcerPrograms struct {
	XdpDropTcpPorts *ebpf.Program `ebpf:"xdp_drop_tcp_ports"`
}

func (p *enforcerPrograms) Close() error {
	return _EnforcerClose(
		p.XdpDropTcpPorts,
	)
}

func _EnforcerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed enforcer_bpfel.o
var _EnforcerBytes []byte
